services:
  nginx:
    image: nginx:latest
    ports:
      - "8888:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    # --- THIS IS THE FIX ---
    # This block tells Docker to load the .env file from the project root
    # and make its variables available to the backend service.
    env_file:
      - .env
    # -----------------------
    depends_on:
      - chromadb

  chromadb:
    image: ghcr.io/chroma-core/chroma:0.4.24
    volumes:
      - chroma_data:/chroma
    ports:
      - "8000:8000"

volumes:
  chroma_data: