services:
  nginx:
    image: nginx:latest
    ports:
      - "8888:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    networks:
      - miso-net

  backend:
    build:
      context: ./backend
    depends_on:
      - chromadb
      - ollama
    networks:
      - miso-net

  chromadb:
    image: ghcr.io/chroma-core/chroma:0.4.24 # <-- VERSION PINNED
    volumes:
      - chroma_data:/chroma
    ports:
      - "8000:8000"
    networks:
      - miso-net

  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    networks:
      - miso-net

volumes:
  chroma_data:
  ollama_data:

networks:
  miso-net: