FROM python:3.11-slim

# Install system utilities
RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*

# Install Python Brains
RUN pip install boto3 requests numpy pandas scipy scikit-learn

# Set workdir
WORKDIR /app
