version: '3.8'

services:
  nginx:
    image: miso-10-8-2025-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8888:80"
    networks:
      - miso-net
    depends_on:
      - backend

  backend:
    image: miso-10-8-2025-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - miso-net
    environment:
      - CHROMA_HOST=chromadb
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      chromadb:
        condition: service_healthy

  chromadb:
    image: ghcr.io/chroma-core/chroma:0.5.0
    networks:
      - miso-net
    volumes:
      - chroma_data:/chroma/chroma
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 5s
      timeout: 10s
      retries: 5

  ollama:
    image: ollama/ollama
    networks:
      - miso-net
    volumes:
      - ollama_data:/root/.ollama

networks:
  miso-net:
    driver: bridge

volumes:
  chroma_data:
    driver: local
  ollama_data:
    driver: local