import os

target_path = "src/modules/safety/sandbox.py"

# We explicitly use double curly braces {{ }} for the JSON parts
# while keeping single curly braces { } for the actual variables we want to inject.
sandbox_code = [
    "import subprocess",
    "import logging",
    "import os",
    "import json",
    "import time",
    "",
    "logger = logging.getLogger('MISO')",
    "",
    "IMAGE_NAME = 'miso-sandbox'",
    "",
    "def build_image():",
    "    \"\"\"Ensures the sandbox image exists.\"\"\"",
    "    try:",
    "        subprocess.run(",
    "            ['docker', 'build', '-t', IMAGE_NAME, '-f', 'Dockerfile.sandbox', '.'],",
    "            check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL",
    "        )",
    "        logger.info('Sandbox Armor: ACTIVE')",
    "    except Exception as e:",
    "        logger.error(f'Failed to build sandbox: {e}')",
    "",
    "def run_code(code_snippet, test_harness):",
    "    # 1. Prepare the payload",
    "    # CRITICAL FIX: We use double curly braces {{ }} for literal dicts inside the f-string",
    "    wrapped_script = f'''",
    "import sys",
    "import json",
    "",
    "try:",
    "    # --- USER CODE START ---",
    "{code_snippet}",
    "    # --- USER CODE END ---",
    "",
    "    # --- TEST HARNESS START ---",
    "{test_harness}",
    "    # --- TEST HARNESS END ---",
    "",
    "    print(json.dumps({{'status': 'passed', 'msg': 'Tests Passed'}}))",
    "except AssertionError as e:",
    "    print(json.dumps({{'status': 'failed', 'msg': 'Assertion Failed'}}))",
    "except Exception as e:",
    "    print(json.dumps({{'status': 'error', 'msg': str(e)}}))",
    "'''",
    "    ",
    "    # 2. Write payload to host disk temporarily",
    "    with open('wrapper.py', 'w') as f:",
    "        f.write(wrapped_script)",
    "",
    "    # 3. Run Docker",
    "    try:",
    "        result = subprocess.run(",
    "            [",
    "                'docker', 'run', '--rm', '--network', 'none',",
    "                '-v', f'{os.getcwd()}/wrapper.py:/app/wrapper.py',",
    "                IMAGE_NAME",
    "            ],",
    "            capture_output=True, text=True, timeout=5",
    "        )",
    "        ",
    "        # 4. Parse Output",
    "        output = result.stdout.strip()",
    "        if not output:",
    "            return False, f'Crash/Timeout: {result.stderr}'",
    "        ",
    "        try:",
    "            data = json.loads(output.splitlines()[-1])",
    "            if data['status'] == 'passed': return 1.0, 'PASSED'",
    "            if data['status'] == 'failed': return 0.4, 'Logic Error'",
    "            return 0.1, f\"Runtime Error: {data['msg']}\"",
    "        except:",
    "            return 0.1, f'Output Parse Error: {output}'",
    "            ",
    "    except subprocess.TimeoutExpired:",
    "        return 0.0, 'Security: Timeout (Possible Infinite Loop)'",
    "    except Exception as e:",
    "        return 0.0, f'Sandbox Failure: {e}'"
]

with open(target_path, 'w') as f:
    f.write("\n".join(sandbox_code))

print("SUCCESS: Sandbox Syntax Repaired.")
