import os

target_path = "src/modules/gan/gladiator.py"
os.makedirs(os.path.dirname(target_path), exist_ok=True)

# We use a list of short strings. This is safe for all terminal buffers.
lines = [
    "import logging",
    "import argparse",
    "import sys",
    "import ast",
    "import os",
    "import re",
    "import google.generativeai as genai",
    "from typing import List, Dict, Any, Tuple",
    "",
    "logger = logging.getLogger('MISO')",
    "logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')",
    "",
    "API_KEY = os.getenv('GEMINI_API_KEY')",
    "if API_KEY:",
    "    genai.configure(api_key=API_KEY)",
    "",
    "def clean_code_block(text: str) -> str:",
    "    pattern = r'```python\\n(.*?)```'",
    "    match = re.search(pattern, text, re.DOTALL)",
    "    if match: return match.group(1).strip()",
    "    return text.replace('```', '').strip()",
    "",
    "def get_best_available_model():",
    "    return 'models/gemini-2.5-flash'",
    "",
    "class BuilderAgent:",
    "    def __init__(self):",
    "        try:",
    "            self.model = genai.GenerativeModel(get_best_available_model())",
    "        except:",
    "            self.model = None",
    "",
    "    def generate(self, context: str, feedback: str = None, auto_test: bool = False) -> str:",
    "        if not self.model: return 'def error(): pass'",
    "        prompt = f'Write a Python function for: {context}.\\nReturn ONLY raw Python code.\\n'",
    "        if auto_test:",
    "            prompt += 'IMPORTANT: Include `if __name__ == \"__main__\":` block at end.\\n'",
    "            prompt += 'Inside that block, write 3 assertions.\\n'",
    "        if feedback:",
    "            prompt += f'\\nCRITICAL: Previous failed.\\nFeedback: {feedback}\\nFix it.'",
    "        try:",
    "            response = self.model.generate_content(prompt)",
    "            return clean_code_block(response.text)",
    "        except Exception as e:",
    "            return f'# Gen Failed: {e}'",
    "",
    "class CriticAgent:",
    "    def evaluate(self, code_snippet: str, external_tests: str = None) -> Tuple[float, str]:",
    "        try:",
    "            ast.parse(code_snippet)",
    "        except SyntaxError as e:",
    "            return 0.0, f'SyntaxError: {e.msg}'",
    "        sandbox_locals = {}",
    "        try:",
    "            if external_tests:",
    "                exec(code_snippet, globals(), sandbox_locals)",
    "                exec(external_tests, globals(), sandbox_locals)",
    "            else:",
    "                exec(code_snippet, globals(), sandbox_locals)",
    "            return 1.0, 'PASSED'",
    "        except AssertionError:",
    "            return 0.4, 'Logic Error: Assertion failed.'",
    "        except Exception as e:",
    "            return 0.1, f'Runtime Error: {e}'",
    "",
    "class GladiatorArena:",
    "    def __init__(self, builder, critic):",
    "        self.builder = builder",
    "        self.critic = critic",
    "",
    "    def fight(self, rounds: int, problem: str, test_harness: str = None) -> Dict[str, Any]:",
    "        logger.info(f'Problem: {problem}')",
    "        best_sol = None",
    "        best_score = -1.0",
    "        last_feedback = None",
    "        auto_test_mode = (test_harness is None)",
    "",
    "        for r in range(rounds):",
    "            cand = self.builder.generate(problem, last_feedback, auto_test=auto_test_mode)",
    "            score, feedback = self.critic.evaluate(cand, test_harness)",
    "            last_feedback = feedback",
    "            logger.info(f'Round {r+1} | Score: {score} | Status: {feedback}')",
    "            if score > best_score:",
    "                best_score = score",
    "                best_sol = cand",
    "                if score == 1.0: break",
    "        return {'best_sol': best_sol, 'best_score': best_score}",
    "",
    "def main():",
    "    parser = argparse.ArgumentParser()",
    "    parser.add_argument('problem', nargs='?')",
    "    parser.add_argument('--rounds', type=int, default=3)",
    "    args = parser.parse_args()",
    "    if not os.getenv('GEMINI_API_KEY'):",
    "        print('ERROR: Set GEMINI_API_KEY')",
    "        return",
    "    arena = GladiatorArena(BuilderAgent(), CriticAgent())",
    "    if args.problem:",
    "        res = arena.fight(rounds=args.rounds, problem=args.problem)",
    "    else:",
    "        print('Running Demo Mode...')",
    "        res = arena.fight(rounds=args.rounds, problem='Write unique_ordered(l)', ",
    "                          test_harness='assert unique_ordered([1,2,2])==[1,2]')",
    "    print('='*40 + '\\nFINAL SOLUTION\\n' + '='*40)",
    "    print(res['best_sol'])",
    "",
    "if __name__ == '__main__':",
    "    main()"
]

with open(target_path, 'w') as f:
    f.write('\n'.join(lines))

print(f"SUCCESS: Gladiator installed to {target_path}")
