# Gauntlet Level 6: The "Direct Route" Test (DE-SIMULATED)
# 1. Reset the buggy file to ensure the ZeroDivisionError exists.
# 2. Run pytest to confirm the ZeroDivisionError.
# 3. Feed the error to the Triage Agent.
# 4. VERIFY: The Triage Agent's new logic routes DIRECTLY to the "Human (Expensive)" brain.
# 5. VERIFY: The Human brain (DE-SIMULATED) successfully fixes the bug.
# 6. VERIFY: pytest test_broken_math.py now passes.

import subprocess
import sys
import os
import asyncio # We still need this to call the async Lizard, just in case
from miso_triage import MisoTriageAgent

TARGET_FILE = "broken_math.py"
TEST_FILE = "test_broken_math.py"

def run_command(command):
    """Helper to run shell commands and return output."""
    result = subprocess.run(command, capture_output=True, text=True, shell=True)
    return result.stdout + result.stderr

def run_gauntlet():
    print("--- GAUNTLET LEVEL 6: 'THE DIRECT ROUTE TEST' (DE-SIMULATED) ---")
    print("This test will verify the Triage Agent's new 'direct-to-Human' logic.\n")
    
    total_cost = 0
    
    # --- PREREQUISITE: Reset the buggy file ---
    print("[GAUNTLET]: Resetting buggy file 'broken_math.py' to its buggy state...")
    try:
        buggy_code = (
            "# This file contains a bug the Lizard brain\n"
            "# is not designed to fix.\n\n"
            "def divide_by(a, b):\n"
            "    # This will cause a ZeroDivisionError if b is 0\n"
            "    return a / b\n\n"
            "def get_average(numbers):\n"
            "    if not numbers:\n"
            "        return 0\n    \n"
            "    # This is the 'bait' bug.\n"
            "    total_sum = sum(numbers)\n"
            "    return divide_by(total_sum, 0)\n"
        )
        with open(TARGET_FILE, 'w') as f:
            f.write(buggy_code)
    except Exception as e:
        print(f"[GAUNTLET]: ERROR! Could not create buggy file: {e}")
        sys.exit(1)

    # We must also have the TDD test file
    if not os.path.exists(TEST_FILE):
        print(f"[GAUNTLET]: ERROR! Test file {TEST_FILE} is missing!")
        print("Please ask me to restore 'test_broken_math.py'.")
        sys.exit(1)
        
    try:
        triage_agent = MisoTriageAgent()
    except Exception as e:
        print(f"CRITICAL: Failed to initialize MisoTriageAgent. Did you set your GOOGLE_API_KEY in .env?")
        print(f"Error: {e}")
        sys.exit(1)

    # --- STEP 1: Confirm initial TDD failure ---
    print(f"\n[GAUNTLET]: Running pytest {TEST_FILE} (expecting ZeroDivisionError)...")
    pytest_error = run_command(f"pytest {TEST_FILE}")
    
    if "failed" not in pytest_error:
        print("[GAUNTLET]: ERROR! TDD is already passing. Test is invalid.")
        sys.exit(1)
    
    if "ZeroDivisionError" not in pytest_error:
        print("[GAGAUNTLET]: ERROR! Test is failing with an unexpected error.")
        sys.exit(1)

    print("[GAUNTLET]: Confirmed. TDD failure detected (ZeroDivisionError).")
    original_code = open(TARGET_FILE, 'r').read()
    
    # --- STEP 2: Triage (Direct-to-Human) ---
    print("\n[GAUNTLET]: Triage Agent is analyzing the complex bug...")
    chosen_brain = triage_agent.decide_brain(pytest_error)
    
    if not chosen_brain or chosen_brain.name != "Human (Expensive)":
        brain_name = chosen_brain.name if chosen_brain else "None"
        print(f"[GAUNTLET]: *** TEST FAILED (Triage Logic) ***")
        print(f"[GAUNTLET]: Triage Agent chose '{brain_name}'!")
        print(f"[GAUNTLET]: It should have routed DIRECTLY to 'Human (Expensive)'.")
        sys.exit(1)

    print(f"[GAUNTLET]: Triage PASSED: Correctly routed to {chosen_brain.name}")
    print(f"[GAUNTLET]: {chosen_brain.name} (DE-SIMULATED) is attempting the fix...")

    # --- STEP 3: Run the Human Brain (Gemini) ---
    # Note: Human 'fix' method is NOT async, it's blocking
    fix_code, cost = chosen_brain.fix(original_code, pytest_error)
    total_cost += cost

    # --- STEP 4: Apply Fix & Verify ---
    if fix_code is None or "def" not in fix_code:
        print("[GAUNTLET]: *** TEST FAILED (Human Failed) ***")
        print("[GAUNTLET]: The DE-SIMULATED Human brain failed to provide a valid fix.")
        print(f"[GAUNTLET]: AI RESPONSE: {fix_code}")
        sys.exit(1)

    print(f"\n[GAUNTLET]: Fix generated by Human (Gemini). Writing to {TARGET_FILE}...")
    open(TARGET_FILE, 'w').write(fix_code)
    
    # --- STEP 5: VERIFY TDD Pass ---
    print(f"[GAUNTLET]: Verifying final fix... running pytest {TEST_FILE} (expecting pass)...")
    pytest_fix_result = run_command(f"pytest {TEST_FILE}")
    
    if "passed" not in pytest_fix_result:
        print("[GAUNTLET]: *** TEST FAILED (Step 5) ***")
        print("[GAUNTLET]: TDD still fails after HUMAN's fix:")
        print(pytest_fix_result)
        sys.exit(1)
        
    print("[GAUNTLET]: *** TEST PASSED (Step 5) ***")
    print(f"[GAUNTLET]: TDD suite for {TEST_FILE} now passes.\n")

    # --- FINAL REPORT ---
    print("--- GAUNTLET LEVEL 6 (DIRECT ROUTE): PASSED ---")
    print("SUMMARY:")
    print("  - Triage Agent CORRECTLY routed complex bug to: Human (Tier 5)")
    print("  - Human Brain (Gemini) CORRECTLY: FIXED")
    print("  - TDD tests: PASSED")
    print(f"  - Total simulated cost: ${total_cost:.4f}")
    print("--- MISO DE-SIMULATED TIER-5 LOGIC IS OPERATIONAL ---")

if __name__ == "__main__":
    run_gauntlet()
