import os

def solve(input_str: str) -> str:
    """
    Reads Bitcoin and Ethereum prices from their respective files,
    calculates the BTC/ETH ratio, and saves a formatted report to 'crypto_ratio.txt'.
    """
    btc_price_file = 'btc_price.txt'
    eth_price_file = 'eth_price.txt'
    report_file = 'crypto_ratio.txt'

    # For demonstration and self-containment, create dummy price files if they don't exist.
    # In a real pipeline, these files would be generated by previous tasks.
    if not os.path.exists(btc_price_file):
        with open(btc_price_file, 'w') as f:
            f.write("68543.21")
    if not os.path.exists(eth_price_file):
        with open(eth_price_file, 'w') as f:
            f.write("3589.67")

    try:
        # Read the price from the Bitcoin price file
        with open(btc_price_file, 'r') as f:
            btc_price_str = f.read().strip()
            if not btc_price_str:
                raise ValueError(f"File {btc_price_file} is empty.")
            btc_price = float(btc_price_str)

        # Read the price from the Ethereum price file
        with open(eth_price_file, 'r') as f:
            eth_price_str = f.read().strip()
            if not eth_price_str:
                raise ValueError(f"File {eth_price_file} is empty.")
            eth_price = float(eth_price_str)

        # Handle potential division by zero
        if eth_price == 0:
            raise ZeroDivisionError("Ethereum price cannot be zero for ratio calculation.")

        # Calculate the ratio (how many ETH for 1 BTC)
        ratio = btc_price / eth_price

        # Format the report string
        report_content = (
            f"Crypto Price Ratio Report\n"
            f"=========================\n"
            f"Bitcoin (BTC) Price: ${btc_price:,.2f}\n"
            f"Ethereum (ETH) Price: ${eth_price:,.2f}\n"
            f"-------------------------\n"
            f"Ratio: 1 BTC = {ratio:.2f} ETH\n"
        )

        # Save the report to the output file
        with open(report_file, 'w') as f:
            f.write(report_content)

        return f"Successfully created crypto ratio report in '{report_file}'."

    except FileNotFoundError as e:
        return f"Error: Input file not found: {e.filename}"
    except ValueError as e:
        return f"Error: Invalid data in price file. Could not convert to a number. Details: {e}"
    except ZeroDivisionError as e:
        return f"Error: Cannot calculate ratio. {e}"
    except Exception as e:
        return f"An unexpected error occurred: {e}"