apiVersion: v1
kind: Secret
metadata:
  name: miso-secrets
type: Opaque
stringData:
  DB_HOST: "miso-phoenix-ledger-prod.cw...us-east-1.rds.amazonaws.com"
  DB_USER: "miso_admin"
  DB_PASS: "MisoPhoenixX_99!"
  DB_NAME: "miso_ledger"

---
# 🧠 THE BRAIN (Control Plane)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: miso-brain
  labels:
    app: brain
spec:
  replicas: 1
  selector:
    matchLabels:
      app: brain
  template:
    metadata:
      labels:
        app: brain
    spec:
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"
      containers:
      - name: api
        # FIX: Use the Master IP so everyone can find the registry
        image: 172.31.16.61:32000/miso-brain:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: miso-secrets
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: brain-service
spec:
  selector:
    app: brain
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort

---
# 💪 THE MUSCLE (Spot Instance)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: miso-muscle
  labels:
    app: muscle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: muscle
  template:
    metadata:
      labels:
        app: muscle
    spec:
      # THE ANCHOR: Force this to run on Spot Instances
      nodeSelector:
        node-role.kubernetes.io/worker: spot
      containers:
      - name: worker
        # FIX: Point to the Master Node's Registry
        image: 172.31.16.61:32000/miso-muscle:v1
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: miso-secrets
        resources:
          requests:
            cpu: "1000m"
            memory: "2Gi"
          limits:
            cpu: "2000m"
            memory: "4Gi"
